### ISSUE TITLE
Email notification?

### ISSUE THREAD

**Issue by jlnbdt** [YunoHost-Apps/vikunja_ynh#14]
Hi,

Thanks a lot for packaging vikunja, this is still a young application but very promising.
Is emailing supposed to work out of the box? I can't receive any notifications.

**Comment by jcn50** [comment]
I think a patch is in progress: https://github.com/YunoHost-Apps/vikunja_ynh/pull/15

**Comment by ericgaspar** [comment]
I am not able to make email working...

I have changed the config like so.
```
mailer:
  # Whether to enable the mailer or not. If it is disabled, all users are enabled right away and password reset is not possible.
  enabled: true
  # SMTP Host
  host: "localhost"
  # SMTP Host port
  port: 25
  # SMTP username
  username: "vikunja"
  # SMTP password
  password: ""
  # Wether to skip verification of the tls certificate on the server
  skiptlsverify: true
  # The default from address when sending emails
  fromemail: "mail@vikunja"
  # The length of the mail queue.
  queuelength: 100
  # The timeout in seconds after which the current open connection to the mailserver will be closed.
  queuetimeout: 30
  # By default, vikunja will try to connect with starttls, use this option to force it to use ssl.
  forcessl: false
```

does anyone have been able to set a working email?
